import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faBell,
  faBookOpen,
  faBullhorn,
  faChartLine,
  faCircleQuestion,
  faCode,
  faComments,
  faCubes,
  faFolderOpen,
  faGamepad,
  faGear,
  faGlobe,
  faHandshake,
  faKey,
  faLaptopCode,
  faMagnifyingGlass,
  faNewspaper,
  faPalette,
  faServer,
  faShieldHalved,
  faScrewdriverWrench,
  faTableColumns,
  faUser,
  faUsers,
  faDice,
  faStar,
  faGem,
  faDna,
  faSkull,
} from '@fortawesome/free-solid-svg-icons'
import { faDiscord } from '@fortawesome/free-brands-svg-icons'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'

const sidebarIcons: Record<string, IconDefinition> = {
  dashboard: faTableColumns,
  servers: faServer,
  minecraft: faCubes,
  discord: faDiscord,
  gamepad: faGamepad,
  games: faGamepad,
  dice: faDice,
  star: faStar,
  gem: faGem,
  dna: faDna,
  skull: faSkull,
  palette: faPalette,
  assets: faPalette,
  handshake: faHandshake,
  talents: faHandshake,
  code: faLaptopCode,
  users: faUser,
  forum: faComments,
  news: faNewspaper,
  chart: faChartLine,
  cluster: faCubes,
  search: faMagnifyingGlass,
  bell: faBell,
  shield: faShieldHalved,
  key: faCode,
  lock: faKey,
  globe: faGlobe,
  folder: faFolderOpen,
  settings: faGear,
  community: faUsers,
  'book-open': faBookOpen,
  'circle-question': faCircleQuestion,
  bullhorn: faBullhorn,
  'screwdriver-wrench': faScrewdriverWrench,
}

export function SidebarIcon({ name }: { name: string }) {
  const icon = sidebarIcons[name] || faGear
  return <FontAwesomeIcon icon={icon} fixedWidth />
}
